libc_a_SOURCES += \
	%D%/abort.c \
	%D%/environ.c \
	%D%/memccpy.S \
	%D%/memchr.S \
	%D%/memcmp.S \
	%D%/memcpy.S \
	%D%/memmove.S \
	%D%/mempcpy.S \
	%D%/memrchr.S \
	%D%/memset.S \
	%D%/rawmemchr.S \
	%D%/setjmp.S \
	%D%/stpcpy.S \
	%D%/stpncpy.S \
	%D%/strchr.S \
	%D%/strcmp.S \
	%D%/strcpy.S \
	%D%/strlen.S \
	%D%/strncmp.S \
	%D%/strncpy.S \
	%D%/sysgetpid.c
